# Generated by Django 6.0.3 on 2026-03-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='stripe_payment_intent_id',
            new_name='razorpay_payment_link_id',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='stripe_payment_link_url',
            new_name='razorpay_payment_link_url',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_charge_id',
            new_name='razorpay_payment_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_payment_intent_id',
            new_name='razorpay_signature',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='stripe_customer_id',
            new_name='razorpay_customer_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(blank=True, choices=[('razorpay', 'Razorpay'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
